apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/hide1080/cnsia-edge-service/k8s?ref=main

# patchesStrategicMerge:
#   - patch-env.yml
patches:
  - path: patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: edge-config

images:
  - name: edge-service
    newName: ghcr.io/hide1080/edge-service
    newTag: latest

replicas:
  - name: edge-service
    count: 1