version: "3.8"

services:
  catalog-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  edge-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  order-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
